# Generated by Django 4.2.4 on 2023-08-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("article_id", models.AutoField(primary_key=True, serialize=False)),
                ("article", models.TextField()),
                ("article_length", models.IntegerField(null=True)),
            ],
        ),
    ]
