# Generated by Django 4.2.4 on 2023-08-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article", old_name="article_id", new_name="id",
        ),
        migrations.RenameField(
            model_name="article", old_name="article_length", new_name="length",
        ),
    ]
