# Generated by Django 4.2.4 on 2023-08-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_rename_article_id_article_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="title",
            field=models.TextField(default="Title unknown"),
        ),
    ]
